version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    tty: true
    init: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    container_name: books
    networks:
      - bookShelf

  db:
    image: postgres:15-alpine
    ports:
      - 5430:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: bookshelf
      POSTGRES_USER: bookshelf
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./webapi/script:/docker-entrypoint-initdb.d
    container_name: postgres
    networks:
      - bookShelf

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: coo4nemu5@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - db
    container_name: pgadmin4
    networks:
      - bookShelf

volumes:
  node_modules:
  dbdata:
  pgadmin4_data:


networks:
  bookShelf:
    external: true
