import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthProvider from '@/app/providers/NextAuth'
import Link from 'next/link'
import CssBaseline from "@mui/material/CssBaseline";
import theme from '@/components/theme';
import { ThemeProvider } from "@mui/material/styles";

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Book Shelf',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp" className='main'>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body className={inter.className}>
          <NextAuthProvider>
            <header>
              <ul>
                <li><Link href="/">top</Link></li>
                <li><Link href="/BookShelf">本棚</Link></li>
              </ul>
            </header>
            {children}
          </NextAuthProvider>
        </body>
      </ThemeProvider>
    </html>
  )
}
